version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:10.19.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Show current branch
          command: |
            echo ${CIRCLE_BRANCH}
      - run: 
          name: Install dependencies
          command: sudo npm install
      - run: 
          name: Build prod files
          command: |
            sudo npm run build
  deploy-to-aws-ec2:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "6a:ea:cc:7e:f4:00:09:5b:6b:cb:e2:04:8f:a7:cd:78"
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Download rsync
          command: sudo apt install rsync
      - run:
          name: Transfer via rsync
          command: rsync -avrP "ssh -e -oStrictHostKeyChecking=no" ~/repo/* ubuntu@ec2-35-84-150-135.us-west-2.compute.amazonaws.com:~/test
      - run:
          name: ssh into server
          command: ssh -oStrictHostKeyChecking=no ubuntu@ec2-35-84-150-135.us-west-2.compute.amazonaws.com
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      #- build:
      #    filters:
      #      branches:
      #        only: 
      #          - production
      - deploy-to-aws-ec2:
          requires:
            - build
          filters:
            branches:
              only: 
                - production

          
